### ISSUE TITLE
Team logo can not be displayed

### ISSUE THREAD

**Issue by Sakura-jun** [ins0/armasquads#66]
In the game which I can see my email some information, but can not see my badge. This can also be seen until very strange.
http://armasquads.com/user/squads/xml/eXYqVZFqL1NZPaYj5ZDBCgU6zrA2SthP/squad.xml

**Comment by ins0** [comment]
Please provide more information about the server you are trying to connect. Please note that Linux Server currently don't allow logos because of a temporary bug in arma.

More Information and suggestions in order to make your squad logo work - look here: 

https://github.com/ins0/armasquads/labels/squad%20logo

**Comment by Sakura-jun** [comment]
I do not know, I just updated the Arma 3, and then enter the game himself built a small server. Then I found that I could not see the badge.

**Comment by ins0** [comment]
There could be multiple reasons why your logo is not shown ingame. Please follow the link to similar issues from other users and try the suggentions on each issue.

**Comment by Sakura-jun** [comment]
Appears to be too long because Remark! 
Thanks for your quick reply！

**Comment by ins0** [comment]
Thanks for the information how to resolve your problem :+1:
